apiVersion: v1
kind: Service
metadata:
  name: customers
  labels:
    app: customers
spec:
  type: {{ .Values.customers.service.type }}
  ports:
    - port: {{ .Values.customers.service.port }}
      targetPort: {{ .Values.customers.service.port }}
      protocol: TCP
  selector:
    app: customers
