apiVersion: v1
kind: Service
metadata:
  name: genai
  labels:
    app: genai
spec:
  type: {{ .Values.genai.service.type }}
  ports:
    - port: {{ .Values.genai.service.port }}
      targetPort: {{ .Values.genai.service.port }}
      protocol: TCP
  selector:
    app: genai
